version: 2

sources:
  - name: raw
    database: PC_DBT_DB
    schema: RAW
    tables:
      - name: customers
      - name: orders
      - name: payments

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null